server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # Spring boot 2.6 이후부터 spring.mvc.pathmatch.matching-strategy 값이 ant_apth_matcher에서 path_pattern_parser로 변경
  main:
    allow-circular-references: true
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://springboot-db.cdqff5qi8oou.ap-northeast-2.rds.amazonaws.com:3306/postdemo?serverTimezone=Asia/Seoul
      username:
      password:


  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true